### PR TITLE
Enable Windows builds

### LINKED ISSUE #32: Support Windows as target OS
I was trying to build diskus with on Windows 7 (Rust 1.37.0, stable-x86_64-pc-windows-msvc toolchain). This failed, as the trait `st::os::unix::fs::MetadataExt` is used in `src/walk.rs`.

<details>
  <summary>Here is the full error message of the failing build from my machine.</summary>

```
$ cargo build
   Compiling diskus v0.5.0 (C:\Users\fabian\rust\diskus)
error[E0433]: failed to resolve: could not find `unix` in `os`
 --> src\walk.rs:3:14
  |
3 | use std::os::unix::fs::MetadataExt;
  |              ^^^^ could not find `unix` in `os`

warning: unused import: `std::os::unix::fs::MetadataExt`
 --> src\walk.rs:3:5
  |
3 | use std::os::unix::fs::MetadataExt;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_imports)] on by default

error[E0599]: no method named `nlink` found for type `std::fs::Metadata` in the current scope
  --> src\walk.rs:27:63
   |
27 |             let unique_id = if metadata.is_file() && metadata.nlink() > 1 {
   |                                                               ^^^^^

error[E0599]: no method named `dev` found for type `std::fs::Metadata` in the current scope
  --> src\walk.rs:28:40
   |
28 |                 Some(UniqueID(metadata.dev(), metadata.ino()))
   |                                        ^^^

error[E0599]: no method named `ino` found for type `std::fs::Metadata` in the current scope
  --> src\walk.rs:28:56
   |
28 |                 Some(UniqueID(metadata.dev(), metadata.ino()))
   |                                                        ^^^

error: aborting due to 4 previous errors

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: Could not compile `diskus`.

To learn more, run the command again with --verbose.  
```
</details>

I dug into the source and came up with a patch that allowed me a compile and run the tool. Basically, I refactored the generation of `UniqueID` into a function and made a explicit distinction between `unix` and `windows` when implementing that function.

<details>
  <summary>Here is the diff of the patch.</summary>

```diff
$ git diff  src
diff --git a/src/walk.rs b/src/walk.rs
index 0125713..580a6e0 100644
--- a/src/walk.rs
+++ b/src/walk.rs
@@ -1,9 +1,11 @@
 use std::collections::HashSet;
 use std::fs;
-use std::os::unix::fs::MetadataExt;
 use std::path::PathBuf;
 use std::thread;

+#[cfg(target_os = "unix")]
+use std::os::unix::fs::MetadataExt;
+
 use crossbeam_channel as channel;

 use rayon;
@@ -18,17 +20,27 @@ enum Message {
     CouldNotReadDir(PathBuf),
 }

+#[cfg(target_os = "unix")]
+fn generate_unique_id(metadata: &std::fs::Metadata) -> Option<UniqueID> {
+    // If the entry has more than one hard link, generate
+    // a unique ID consisting of device and inode in order
+    // not to count this entry twice.
+    if metadata.is_file() && metadata.nlink() > 1 {
+        Some(UniqueID(metadata.dev(), metadata.ino()))
+    } else {
+        None
+    }
+}
+
+#[cfg(target_os = "windows")]
+fn generate_unique_id(_metadata: &std::fs::Metadata) -> Option<UniqueID> {
+    None
+}
+
 fn walk(tx: channel::Sender<Message>, entries: &[PathBuf]) {
     entries.into_par_iter().for_each_with(tx, |tx_ref, entry| {
         if let Ok(metadata) = entry.symlink_metadata() {
-            // If the entry has more than one hard link, generate
-            // a unique ID consisting of device and inode in order
-            // not to count this entry twice.
-            let unique_id = if metadata.is_file() && metadata.nlink() > 1 {
-                Some(UniqueID(metadata.dev(), metadata.ino()))
-            } else {
-                None
-            };
+            let unique_id = generate_unique_id(&metadata);

             let size = metadata.len();
```
</details>

While it serves my immediate usecase, the Windows implementation is incorrect/incomplete, as there is no handling of [NTFS Hard Links and Junctions](https://docs.microsoft.com/en-us/windows/win32/fileio/hard-links-and-junctions). A quick search with cargo revealed https://crates.io/crates/junction which would probably be a suitable candidate for coming up with a proper implementation.

The issue I'd like to raise is whether diskus should have Windows support. If so, is the approach via `[cfg(target_os = "...")]` acceptable for diskus. I found [a discussion in the Rust forum](https://users.rust-lang.org/t/platform-specific-use-statements/6923) that contains links to similar branching in the `libc` crate source.

### PR DESCRIPTION
**Pull request by fawick**
Fixes #32.

### CODE REVIEW

**Comment by fawick** [comment]
@sharkdp I am at a total loss why the 1.29 build fails (e.g. https://travis-ci.org/sharkdp/diskus/jobs/587587254). I'd be happy to hear your thoughts.

**Comment by sharkdp** [comment]
> @sharkdp I am at a total loss why the 1.29 build fails (e.g. https://travis-ci.org/sharkdp/diskus/jobs/587587254). I'd be happy to hear your thoughts.

Don't worry. I've updated the min. required version to Rust 1.34. It was very outdated.

**Comment by sharkdp** [comment]
Thank you!

**Comment by fawick** [comment]
> Don't worry. I've updated the min. required version to Rust 1.34. It was very outdated.

Thank you for your help, that's much appreciated.

**Pull request merged**
