### PR TITLE
Publish lock file with crate

### PR DESCRIPTION
**Pull request by polyzen**

### CODE REVIEW

**Comment by sharkdp** [comment]
Thank you for your contribution. The build currently fails.

**Comment by amilajack** [comment]
[Here is the correct config](https://github.com/amilajack/diskus/commit/7fefe2d71f6a9c009640615c58e5754d8d3ce074). We will need to publish on nightly cargo. This features is unstable. But CI is not configured to test against nightly. Only stable is supported by our CI config now

**Comment by polyzen** [comment]
Oh jeez. If that's the case, I may be better off trying to get it stabilized at this point.

Edit: Left a message here:
https://github.com/rust-lang/cargo/issues/5654

**Comment by polyzen** [comment]
Will make a new PR once `publish-lockfile` is stabilized.

**Pull request closed without merging**
