### PR TITLE
Add AUR listing

### PR DESCRIPTION
**Pull request by SergeyKasmy**
Created an Arch Linux package for personal use. Decided to upload to the AUR. You can add the link to the description for other to see and use, too :)

P.S. I named it du-dup-bin for multiple reasons. Firstly, there already is a dup package, so I guessed it wouldn't be a problem to name it du-dup like in the case with cargo. And secondly, -bin because it is a prebuilt package, a package that compiles from source  wouldn't have such a suffix.

### CODE REVIEW

**Comment by polyzen** [comment]
Way ahead of you :) https://aur.archlinux.org/packages/dup-rs/

Edit: Oh, I see yours is a binary package.

**Comment by grayk79** [comment]
Wow, didn't notice there had already been a package. The name isn't that obvious to be honest. I wouldn't make mine if I found yours but too late, I guess. And yeah, mine is binary, I don't like compiling stuff

**Comment by SergeyKasmy** [comment]
Wow, didn't notice there had already been a package. The name isn't that obvious to be honest. I wouldn't make mine if I found yours but too late, I guess. And yeah, mine is binary, I don't like compiling stuff

**Comment by polyzen** [comment]
I could change it to `du-dup`. I figure if it eventually ends up in the repos, it would probably be renamed to `dup` anyhow. (This was created before the crate :p.)

**Comment by sharkdp** [comment]
You guys are fast .. I haven't even announced this officially :smile:

I think we should look for an entirely new name (see #9) before we start attaching more pre- and post-fixes. What do you think?

**Comment by polyzen** [comment]
> You guys are fast .. I haven't even announced this officially smile

<.< https://lobste.rs/s/vh6uhw/minimal_fast_alternative_du_sh

> I think we should look for an entirely new name (see #9) before we start attaching more pre- and post-fixes. What do you think?

:+1:

**Comment by SergeyKasmy** [comment]
[¯\\\_(ツ)_/¯](https://www.reddit.com/r/commandline/comments/9tcaa1/a_minimal_fast_alternative_to_du_sh_dup_is_a_very/)

(missclicked, oops)

**Comment by sharkdp** [comment]
> <.< [lobste.rs/s/vh6uhw/minimal_fast_alternative_du_sh](https://lobste.rs/s/vh6uhw/minimal_fast_alternative_du_sh)

> ¯\_(ツ)_/¯

:see_no_evil: :smile: 

I have renamed the project to `diskus`. It looks like the name is available on the AUR: https://aur.archlinux.org/packages/?O=0&K=diskus

**Pull request closed without merging**
